ci: Rework ghcr pipeline to work with java 25 #409
* refactor(deps): Remove unnecessary code  #409

* ci: Try and fix the upload to ghcr pipeline  #409

* ci: Fix branch condition to run on this branch  #409

* ci: Implement fail-fast false  #409

* ci: Modify on-push action to correctly work with the frontend  #409

* ci: Format file  #409

* ci: Fix path to dockerfile  #409

* ci: Add back release please to pipeline  #409

* ci: Use pre-defined context to improve readability  #409

* ci: Format yml  #409

* ci: Adjust e2e command to work with the new context  #409

* build(docker): Change context again to match backend  #409

* ci: Remove branch in on-push main  #409

* ci: Fix e2e script and remove fail-fast  #409

diff --git a/docker/e2e-application-start b/docker/e2e-application-start
--- a/docker/e2e-application-start
+++ b/docker/e2e-application-start
@@ -1,12 +1,12 @@
 #!/bin/bash
 git_base_path=$(git rev-parse --show-toplevel)
 
-echo "**Changing into the docker directory**"
-cd "$git_base_path"/docker
+echo "**Changing into the root directory**"
+cd "$git_base_path" || { echo "Could not find git_base_path. Aborting"; exit 1; }
 
 echo "**Merging and running the docker-compose file**"
 echo "----------------------------------------------------------------"
-docker compose -f docker-compose.yml -f docker-compose.e2e.yml --profile backend up --build
+docker compose -f docker/docker-compose.yml -f docker/docker-compose.e2e.yml --profile backend up --build
 
 echo "**Stopping the docker containers**"
-trap 'docker compose down -v' EXIT
+trap 'docker compose -f docker/docker-compose.yml -f docker/docker-compose.e2e.yml down -v' EXIT
